name: my-check
on: 
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out your repository
        uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Install project
        run: poetry install
      - name: Start tests
        run: poetry run pytest